version: '3.3'

networks:
  default:

services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3307:3306
    networks:
      - default

  wordpress:
    depends_on:
      - db
    image: wordpress:6.0-php8.0-apache
    ports:
      - 5000:80
    restart: always
    volumes:
      - ./src/themes/example-theme:/var/www/html/wp-content/themes/example-theme:ro
      - ./src/plugins/example-plugin:/var/www/html/wp-content/plugins/example-plugin:ro
      - ./www:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    networks:
      - default

  wp-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: www-data
    volumes:
      - ./src/themes/example-theme:/var/www/html/wp-content/themes/example-theme:ro
      - ./src/plugins/example-plugin:/var/www/html/wp-content/plugins/example-plugin:ro
      - ./www:/var/www/html:rw
    command: sh -c '
      wp core install 
        --path="/var/www/html" 
        --url=http://localhost:5000 
        --title="Meu Wordpress com Docker" 
        --admin_user=admin 
        --admin_password=secret 
        --admin_email=seuemail@seuprovedor.com'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
    networks:
      - default
